{% set name = "sphinxcontrib-httpexample" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 05999d36dd4a91f1146a3c9f5cd1faf721b8960ba3d4ee6d951b1a80cec0ea8f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=2
    - pip
    - pytest-runner
  run:
    - python >=2
    - astunparse
    - docutils
    - sphinx
    - sphinxcontrib-httpdomain

test:
  imports:
    - sphinxcontrib

about:
  home: https://github.com/collective/sphinxcontrib-httpexample
  license: GPL-2.0
  license_family: GPL
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Adds example directive for sphinx-contrib httpdomain.
  description: |
    sphinxcontrib-httpexample enhances sphinxcontrib-httpdomain, a Sphinx domain
    extension for describing RESTful HTTP APIs in detail, with a simple call
    example directive. The new directive provided by this extension generates
    RESTful HTTP API call examples for different tools from a single HTTP
    request example.
  doc_url: http://sphinxcontrib-httpexample.readthedocs.io/
  dev_url: https://github.com/collective/sphinxcontrib-httpexample

extra:
  recipe-maintainers:
    - carlodri
