{% set name = "sphinxcontrib-httpexample" %}
{% set version = "2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 881881e0125e0f75c15e46564a82252dd8a68c499348d2d9e42cd52c213a58ad

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - pytest-runner
  run:
    - python >={{ python_min }}
    - importlib-metadata
    - importlib-resources
    - docutils
    - sphinx
    - sphinxcontrib-httpdomain

test:
  requires:
    - python {{ python_min }}
  imports:
    - sphinxcontrib

about:
  home: https://github.com/collective/sphinxcontrib-httpexample
  license: GPL-2.0-only
  license_file: LICENSE
  summary: Adds example directive for sphinx-contrib httpdomain.
  description: |
    sphinxcontrib-httpexample enhances sphinxcontrib-httpdomain, a Sphinx domain
    extension for describing RESTful HTTP APIs in detail, with a simple call
    example directive. The new directive provided by this extension generates
    RESTful HTTP API call examples for different tools from a single HTTP
    request example.
  doc_url: http://sphinxcontrib-httpexample.readthedocs.io/
  dev_url: https://github.com/collective/sphinxcontrib-httpexample

extra:
  recipe-maintainers:
    - carlodri
